name: Deploy to GCP
run-name: ${{ github.actor }} is deploying to GCP
on:
  - push
permissions:
  contents: read
  id-token: write
jobs:
  deploy-to-gcp:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: node-setup
        name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - id: oidc-auth
        name: Authenticate to GCP with OIDC
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/454968290762/locations/global/workloadIdentityPools/default-pool/providers/github
          service_account: pulumi-deployer@pulumi-nextjs-dev.iam.gserviceaccount.com
        
      - id: docker-auth
        name: Authenticate Docker with GCR
        uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io' # or REGION-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.oidc-auth.outputs.access_token }}'
      
      - id: gcloud-setup
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: gcloud-info
        name: gcloud CLI info
        run: gcloud info

      - id: npm-install
        name: NPM install
        run: npm install

      - id: pulumi-preview
        name: Pulumi preview
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: dev
          cloud-url: file://~
          upsert: true
        env:
          GOOGLE_PROJECT: pulumi-nextjs-dev
          GOOGLE_REGION: us-central1
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}