name: Deploy to GCP
run-name: ${{ github.actor }} is deploying to GCP
on:
  - push
permissions:
  contents: read
  id-token: write
env:
  PULUMI_STACK_BUCKET_URL: gs://pulumi-nextjs-gcp-dev-stack/
  PROJECT_ID: pulumi-nextjs-dev
  LOCATION: us-central1
jobs:
  deploy-to-gcp:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: node-setup
        name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - id: oidc-auth
        name: Authenticate to GCP with OIDC
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/454968290762/locations/global/workloadIdentityPools/default-pool/providers/github
          service_account: pulumi-deployer@pulumi-nextjs-dev.iam.gserviceaccount.com
        
      - id: docker-auth
        name: Authenticate Docker with GCR
        uses: 'docker/login-action@v2'
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.oidc-auth.outputs.access_token }}
      
      - id: gcloud-setup
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: gcloud-info
        name: gcloud CLI info
        run: gcloud info

      - id: gcloud-create-stack-bucket
        name: Create dev stack bucket
        run:  gcloud storage buckets create ${{ env.PULUMI_STACK_BUCKET_URL }} --project=${{ env.PROJECT_ID }} --location=${{ env.LOCATION }} --public-access-prevention
        continue-on-error: true

      - id: npm-install
        name: NPM install
        run: npm install

      - id: pulumi-up
        name: Pulumi up
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
          cloud-url: ${{ env.PULUMI_STACK_BUCKET_URL }}
          upsert: true